#!/usr/bin/env node
/**
 * sync_core.js — rebuilds site/clean-copy-core.js from the extension's
 * background.js (the pure conversion part) wrapped in the UMD shell.
 * Single source of truth: extension-clean-copy/background.js.
 * Firefox copy is kept identical too. Run: node tools/sync_core.js
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const BG = path.join(ROOT, 'extension-clean-copy/background.js');
const FF = path.join(ROOT, 'extension-clean-copy-firefox/background.js');
const CORE = path.join(ROOT, 'site/clean-copy-core.js');

let src = fs.readFileSync(BG, 'utf8');
src = src.split('/* \u2500\u2500 Pro: custom cleanup rules')[0];

const umd =
  '/**\n' +
  ' * Clean Copy \u2014 shared HTML->Markdown / text-cleaning core.\n' +
  ' * GENERATED by tools/sync_core.js from extension-clean-copy/background.js.\n' +
  ' * Do not edit by hand \u2014 edit background.js and re-run sync_core.js.\n' +
  ' */\n' +
  '(function (root, factory) {\n' +
  "  if (typeof module === 'object' && module.exports) module.exports = factory();\n" +
  '  else root.CleanCopyCore = factory();\n' +
  "})(typeof self !== 'undefined' ? self : this, function () {\n\n" +
  src.trim() +
  '\n\n  return { cleanText, htmlToMarkdown };\n});\n';

fs.writeFileSync(CORE, umd);
fs.copyFileSync(BG, FF);
console.log('synced: site/clean-copy-core.js + firefox background.js');
