#!/usr/bin/env node
/**
 * sync_core.js — rebuilds site/clean-copy-core.js from the extension's
 * background.js (the pure conversion part) wrapped in the UMD shell.
 * Single source of truth: extension-clean-copy/background.js.
 * Firefox copy is kept identical too. Run: node tools/sync_core.js
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const BG = path.join(ROOT, 'extension-clean-copy/background.js');
const FF = path.join(ROOT, 'extension-clean-copy-firefox/background.js');
const FULL = path.join(ROOT, 'tools/clean_copy_core.js'); // full core incl. Pro rules + batchConvert
const CORE = path.join(ROOT, 'site/clean-copy-core.js');

// The web tool calls CleanCopyCore.batchConvert, so the site core must be the
// FULL shared core (tools/clean_copy_core.js), not the truncated background
// extraction. Firefox still gets the verbatim background.js.
let src = fs.readFileSync(FULL, 'utf8');
const umd = src.replace(
  ' * Extracted verbatim from the extension\'s background.js (same code the\n * Chrome/Firefox extensions run), so web tool and extension behave identically.',
  ' * GENERATED by tools/sync_core.js from tools/clean_copy_core.js.\n * Do not edit by hand \u2014 edit tools/clean_copy_core.js and re-run sync_core.js.'
);

fs.writeFileSync(CORE, umd);
// Obsidian plugin uses the exact same full core.
fs.writeFileSync(path.join(ROOT, 'obsidian-plugin/core.js'), umd);
// CLI keeps its own verbatim copy of the full core.
fs.copyFileSync(FULL, path.join(ROOT, 'clean-copy-cli/clean_copy_core.js'));
fs.copyFileSync(BG, FF);
// GitHub repo copy (clean-copy-repo/background.js) must stay identical too.
fs.copyFileSync(BG, path.join(ROOT, 'clean-copy-repo/background.js'));
console.log('synced: site core + obsidian + CLI core + firefox background.js + repo background.js');
